### ISSUE TITLE
Doesnot work below Android 5.0

### ISSUE THREAD

**Issue by showdawn** [glomadrian/dashed-circular-progress#4]
Caused by: java.lang.NoClassDefFoundError: com.github.glomadrian.dashedcircularprogress.R$styleable

Caused by: java.lang.NoClassDefFoundError: com.github.glomadrian.dashedcircularprogress.R$styleable
            at com.github.glomadrian.dashedcircularprogress.DashedCircularProgress.init(DashedCircularProgress.java:101)
            at com.github.glomadrian.dashedcircularprogress.DashedCircularProgress.<init>(DashedCircularProgress.java:51)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at android.view.LayoutInflater.createView(LayoutInflater.java:586)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at info.androidhive.sos.activities.HomeFragment.onCreateView(HomeFragment.java:23)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:795)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:998)
            at android.app.BackStackRecord.run(BackStackRecord.java:622)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1330)
            at android.app.Activity.performStart(Activity.java:4474)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1928)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1980)
            at android.app.ActivityThread.access$600(ActivityThread.java:122)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1146)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4340)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by WebnetMobile** [comment]
Works for me on 4.x w/o problems. Try w/o minify (proguard)
